import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand-dark": "#330C2F",
        "accent-purple": "#7B287D",
        surface: "#faf9fb",
        "surface-dim": "#dadadc",
        "surface-bright": "#faf9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f6",
        "surface-container": "#eeedf0",
        "surface-container-high": "#e8e8ea",
        "surface-container-highest": "#e3e2e4",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#42474d",
        "inverse-surface": "#2f3033",
        "inverse-on-surface": "#f1f0f3",
        outline: "#73777e",
        "outline-variant": "#c2c7ce",
        "surface-tint": "#42617d",
        primary: "#42617d",
        "on-primary": "#ffffff",
        "primary-container": "#a7c7e7",
        "on-primary-container": "#34536f",
        "inverse-primary": "#aacaea",
        secondary: "#6b5779",
        "on-secondary": "#ffffff",
        "secondary-container": "#f1d6ff",
        "on-secondary-container": "#705b7d",
        tertiary: "#7b572d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ebbb88",
        "on-tertiary-container": "#6c4a21",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#faf9fb",
        "on-background": "#1a1c1e",
        "surface-variant": "#e3e2e4",
      },
      fontFamily: {
        heading: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        code: ["var(--font-jetbrains-mono)", "monospace"],
      },
      spacing: {
        "unit": "4px",
        "cell-gap": "12px",
      },
      borderRadius: {
        neo: "10px",
        "neo-sm": "4px",
      },
    },
  },
  plugins: [],
} satisfies Config;
